name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: Lafactorial/AnyKernel31
        ref: sweetk6a
        path: zipper

    - name: Android kernel build
      uses: Keinamvy/android-kernel-actions@master
      id: build
      env:
        NAME: VantomKernel_KSU
      with:
        arch: arm64
        compiler: clang/15
        defconfig: sweet_defconfig
        image: Image

    - name: Release build
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHANNEL_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: Kernel is built!, took ${{ steps.build.outputs.elapsed_time }} seconds.
        document: ${{ github.workspace }}/${{ steps.build.outputs.outfile }}.zip
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          zipper/
          !zipper/.gitignore
          !zipper/README.md
        compression-level: 9
        name: ${{ steps.build.outputs.outfile }}
